Models/PagoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Primera.Models
{
    public class PagoesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PagoesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Pagoes
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Pagos.Include(p => p.Ticket);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Pagoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pago = await _context.Pagos
                .Include(p => p.Ticket)
                .FirstOrDefaultAsync(m => m.Id_Pago == id);
            if (pago == null)
            {
                return NotFound();
            }

            return View(pago);
        }

        // GET: Pagoes/Create
        public IActionResult Create()
        {
            ViewData["Id_Ticket"] = new SelectList(_context.Tickets, "Id_Ticket", "NoPlaca");
            return View();
        }

        // POST: Pagoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id_Pago,Id_Ticket,MontoPago,FechaPago,MetodoPago,EstadoPago")] Pago pago)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pago);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Id_Ticket"] = new SelectList(_context.Tickets, "Id_Ticket", "NoPlaca", pago.Id_Ticket);
            return View(pago);
        }

        // GET: Pagoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pago = await _context.Pagos.FindAsync(id);
            if (pago == null)
            {
                return NotFound();
            }
            ViewData["Id_Ticket"] = new SelectList(_context.Tickets, "Id_Ticket", "NoPlaca", pago.Id_Ticket);
            return View(pago);
        }

        // POST: Pagoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id_Pago,Id_Ticket,MontoPago,FechaPago,MetodoPago,EstadoPago")] Pago pago)
        {
            if (id != pago.Id_Pago)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pago);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PagoExists(pago.Id_Pago))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Id_Ticket"] = new SelectList(_context.Tickets, "Id_Ticket", "NoPlaca", pago.Id_Ticket);
            return View(pago);
        }

        // GET: Pagoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pago = await _context.Pagos
                .Include(p => p.Ticket)
                .FirstOrDefaultAsync(m => m.Id_Pago == id);
            if (pago == null)
            {
                return NotFound();
            }

            return View(pago);
        }

        // POST: Pagoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var pago = await _context.Pagos.FindAsync(id);
            if (pago != null)
            {
                _context.Pagos.Remove(pago);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PagoExists(int id)
        {
            return _context.Pagos.Any(e => e.Id_Pago == id);
        }
    }
}

Models/TicketsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Primera.Models
{
    public class TicketsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TicketsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Tickets
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Tickets.Include(t => t.EspacioEstacionamiento).Include(t => t.Tarifa).Include(t => t.Vehiculo);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Tickets/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket = await _context.Tickets
                .Include(t => t.EspacioEstacionamiento)
                .Include(t => t.Tarifa)
                .Include(t => t.Vehiculo)
                .FirstOrDefaultAsync(m => m.Id_Ticket == id);
            if (ticket == null)
            {
                return NotFound();
            }

            return View(ticket);
        }

        // GET: Tickets/Create
        public IActionResult Create()
        {
            ViewData["Id_Espacio"] = new SelectList(_context.EspacioEstacionamientos, "Id_Espacio", "Estado");
            ViewData["Id_Tarifa"] = new SelectList(_context.Tarifas, "Id_Tarifa", "Descripcion");
            ViewData["NoPlaca"] = new SelectList(_context.Vehiculos, "NoPlaca", "NoPlaca");
            return View();
        }

        // POST: Tickets/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id_Ticket,NoPlaca,Id_Espacio,Fecha_hora_entrada,Fecha_hora_salida,Id_Tarifa,PagoTotal")] Ticket ticket)
        {
            if (ModelState.IsValid)
            {
                _context.Add(ticket);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Id_Espacio"] = new SelectList(_context.EspacioEstacionamientos, "Id_Espacio", "Estado", ticket.Id_Espacio);
            ViewData["Id_Tarifa"] = new SelectList(_context.Tarifas, "Id_Tarifa", "Descripcion", ticket.Id_Tarifa);
            ViewData["NoPlaca"] = new SelectList(_context.Vehiculos, "NoPlaca", "NoPlaca", ticket.NoPlaca);
            return View(ticket);
        }

        // GET: Tickets/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket = await _context.Tickets.FindAsync(id);
            if (ticket == null)
            {
                return NotFound();
            }
            ViewData["Id_Espacio"] = new SelectList(_context.EspacioEstacionamientos, "Id_Espacio", "Estado", ticket.Id_Espacio);
            ViewData["Id_Tarifa"] = new SelectList(_context.Tarifas, "Id_Tarifa", "Descripcion", ticket.Id_Tarifa);
            ViewData["NoPlaca"] = new SelectList(_context.Vehiculos, "NoPlaca", "NoPlaca", ticket.NoPlaca);
            return View(ticket);
        }

        // POST: Tickets/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id_Ticket,NoPlaca,Id_Espacio,Fecha_hora_entrada,Fecha_hora_salida,Id_Tarifa,PagoTotal")] Ticket ticket)
        {
            if (id != ticket.Id_Ticket)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(ticket);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TicketExists(ticket.Id_Ticket))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Id_Espacio"] = new SelectList(_context.EspacioEstacionamientos, "Id_Espacio", "Estado", ticket.Id_Espacio);
            ViewData["Id_Tarifa"] = new SelectList(_context.Tarifas, "Id_Tarifa", "Descripcion", ticket.Id_Tarifa);
            ViewData["NoPlaca"] = new SelectList(_context.Vehiculos, "NoPlaca", "NoPlaca", ticket.NoPlaca);
            return View(ticket);
        }

        // GET: Tickets/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket = await _context.Tickets
                .Include(t => t.EspacioEstacionamiento)
                .Include(t => t.Tarifa)
                .Include(t => t.Vehiculo)
                .FirstOrDefaultAsync(m => m.Id_Ticket == id);
            if (ticket == null)
            {
                return NotFound();
            }

            return View(ticket);
        }

        // POST: Tickets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var ticket = await _context.Tickets.FindAsync(id);
            if (ticket != null)
            {
                _context.Tickets.Remove(ticket);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TicketExists(int id)
        {
            return _context.Tickets.Any(e => e.Id_Ticket == id);
        }
    }
}

Controllers/TarifasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Primera.Models;

namespace Primera.Controllers
{
    public class TarifasController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TarifasController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Tarifas
        public async Task<IActionResult> Index()
        {
            return View(await _context.Tarifas.ToListAsync());
        }

        // GET: Tarifas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tarifa = await _context.Tarifas
                .FirstOrDefaultAsync(m => m.Id_Tarifa == id);
            if (tarifa == null)
            {
                return NotFound();
            }

            return View(tarifa);
        }

        // GET: Tarifas/Create
        public IActionResult Create()
        {
            CargarListaTarifas();   // <- Llenamos el ViewBag con la lista para el dropdown
            return View();
        }

        // POST: Tarifas/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id_Tarifa,TipoTarifa,Monto,Descripcion")] Tarifa tarifa)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tarifa);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            CargarListaTarifas();   // <- Si hay error, volver a llenar el dropdown
            return View(tarifa);
        }

        // GET: Tarifas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tarifa = await _context.Tarifas.FindAsync(id);
            if (tarifa == null)
            {
                return NotFound();
            }

            CargarListaTarifas(tarifa.Id_Tarifa);   // <- Llenamos el ViewBag con selección actual
            return View(tarifa);
        }

        // POST: Tarifas/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id_Tarifa,TipoTarifa,Monto,Descripcion")] Tarifa tarifa)
        {
            if (id != tarifa.Id_Tarifa)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tarifa);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TarifaExists(tarifa.Id_Tarifa))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            CargarListaTarifas(tarifa.Id_Tarifa);  // <- Si hay error, volver a llenar el dropdown
            return View(tarifa);
        }

        // GET: Tarifas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tarifa = await _context.Tarifas
                .FirstOrDefaultAsync(m => m.Id_Tarifa == id);
            if (tarifa == null)
            {
                return NotFound();
            }

            return View(tarifa);
        }

        // POST: Tarifas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tarifa = await _context.Tarifas.FindAsync(id);
            if (tarifa != null)
            {
                _context.Tarifas.Remove(tarifa);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TarifaExists(int id)
        {
            return _context.Tarifas.Any(e => e.Id_Tarifa == id);
        }

        /// <summary>
        /// Método para llenar el ViewBag con la lista de tarifas (ID como valor, TipoTarifa como texto).
        /// </summary>
        /// <param name="selectedId">El Id seleccionado (opcional).</param>
        private void CargarListaTarifas(int? selectedId = null)
        {
            var tarifas = _context.Tarifas.ToList();
            ViewBag.Id_Tarifa = new SelectList(tarifas, "Id_Tarifa", "TipoTarifa", selectedId);
        }
    }
}

Views/Shared/_Layout.cshtml
@{
    var userEmail = User.Identity.Name ?? "Usuario";
    var userName = userEmail.Contains("@") ? userEmail.Substring(0, userEmail.IndexOf("@")) : userEmail;
}

<!DOCTYPE html>
<html lang="es" data-bs-theme="light">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>@ViewData["Title"] - Parqueo</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" rel="stylesheet" />
    <style>
        #sidebar-wrapper {
            min-width: 220px;
            max-width: 220px;
            transition: all 0.3s;
        }

            #sidebar-wrapper.d-none {
                margin-left: -220px;
            }

        #page-content-wrapper {
            transition: all 0.3s;
        }

        /* Caja flotante de confirmación */
        #logoutConfirm {
            position: fixed;
            top: 80px;
            right: 20px;
            z-index: 2000;
            display: none;
            min-width: 260px;
        }
        /* 🎨 Colores personalizados solo para el botón del modo oscuro */
        :root[data-bs-theme='light'] #themeToggle {
            background-color: #f8f9fa; /* fondo claro */
            border-color: #6c757d;
            color: #212529; /* texto oscuro */
        }

            :root[data-bs-theme='light'] #themeToggle:hover {
                background-color: #e9ecef;
            }

        :root[data-bs-theme='dark'] #themeToggle {
            background-color: #1e1e1e; /* fondo oscuro */
            border-color: #0dcaf0; /* borde celeste */
            color: #0dcaf0; /* ícono celeste */
        }

            :root[data-bs-theme='dark'] #themeToggle:hover {
                background-color: #0dcaf0;
                color: #000;
            }

    </style>
</head>
<body>
    <div id="wrapper" class="d-flex">

        <!-- Sidebar -->
        <nav id="sidebar-wrapper" class="border-end sidebar p-3">
            <h5 class="fw-bold">Panel</h5>
            <ul class="nav flex-column">
                <li class="nav-item"><a class="nav-link" asp-controller="Dashboard" asp-action="Index"><i class="bi bi-speedometer2"></i> Dashboard</a></li>
                <li class="nav-item"><a class="nav-link" asp-controller="Clientes" asp-action="Index"><i class="bi bi-person-vcard"></i> Clientes</a></li>
                <li class="nav-item"><a class="nav-link" asp-controller="EspacioEstacionamientoes" asp-action="Index"><i class="bi bi-square"></i> Espacios</a></li>
                <li class="nav-item"><a class="nav-link" asp-controller="TipoVehiculoes" asp-action="Index"><i class="bi bi-truck"></i> Tipo Vehículo</a></li>
                <li class="nav-item"><a class="nav-link" asp-controller="Vehiculos" asp-action="Index"><i class="bi bi-car-front"></i> Vehículos</a></li>
                <li class="nav-item"><a class="nav-link" asp-controller="Tarifas" asp-action="Index"><i class="bi bi-tags"></i> Tarifas</a></li>
                <li class="nav-item"><a class="nav-link" asp-controller="Tickets" asp-action="Index"><i class="bi bi-ticket"></i> Tickets</a></li>
                <li class="nav-item"><a class="nav-link" asp-controller="Pagoes" asp-action="Index"><i class="bi bi-cash"></i> Pagos</a></li>
            </ul>
        </nav>

        <!-- Contenido -->
        <div id="page-content-wrapper" class="flex-grow-1">

            <!-- Navbar -->
            <nav class="navbar navbar-expand-lg bg-body-tertiary border-bottom shadow-sm">
                <div class="container-fluid">
                    <button id="sidebar-toggle-btn" class="btn me-2"><i class="bi bi-list"></i></button>

                    <a class="navbar-brand fw-bold" asp-controller="Home" asp-action="Index">Parqueo</a>

                    <div class="collapse navbar-collapse" id="mainNavbar">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item"><a class="nav-link" asp-controller="Home" asp-action="Index">Inicio</a></li>
                            <li class="nav-item"><a class="nav-link" asp-controller="Home" asp-action="Privacy">Privacidad</a></li>
                        </ul>

                        <div class="d-flex align-items-center ms-auto">
                            <!-- Modo oscuro -->
                            <button id="themeToggle" class="btn btn-outline-secondary me-2" title="Cambiar tema">
                                <i class="bi bi-sun" id="themeIcon"></i>
                            </button>

                            <!-- Menú usuario -->
                            <div class="dropdown">
                                <a href="#" class="btn btn-outline-primary dropdown-toggle" data-bs-toggle="dropdown">
                                    <i class="bi bi-person-circle me-1"></i> @userName
                                </a>
                                <ul class="dropdown-menu dropdown-menu-end">
                                    <li>
                                        <button type="button" class="dropdown-item text-danger" id="btnLogout">
                                            <i class="bi bi-box-arrow-right me-2"></i> Cerrar sesión
                                        </button>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </nav>

            <div class="container mt-4">
                @RenderBody()
            </div>

            <footer class="footer mt-auto py-3 border-top text-muted text-center">
                <div class="container">
                    &copy; 2025 - Parqueo - <a asp-controller="Home" asp-action="Privacy">Privacidad</a>
                </div>
            </footer>
        </div>
    </div>

    <!-- Caja flotante de confirmación -->
    <div id="logoutConfirm" class="card border-danger shadow">
        <div class="card-body p-3">
            <h6 class="text-danger fw-bold mb-2"><i class="bi bi-box-arrow-right"></i> Confirmar cierre</h6>
            <p class="mb-3">¿Deseas cerrar sesión, @userName?</p>
            <div class="d-flex justify-content-end gap-2">
                <button class="btn btn-secondary btn-sm" id="cancelLogout">No</button>
                <form method="post" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="/" id="logoutForm">
                    <button type="submit" class="btn btn-danger btn-sm">Sí, cerrar</button>
                </form>
            </div>
        </div>
    </div>

    <!-- Scripts -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    <script>
        // Mostrar/Ocultar Sidebar
        document.getElementById('sidebar-toggle-btn').addEventListener('click', () => {
            document.getElementById('sidebar-wrapper').classList.toggle('d-none');
        });

        // Tema oscuro persistente
        const themeIcon = document.getElementById('themeIcon');
        const savedTheme = localStorage.getItem('theme') || 'light';
        document.documentElement.setAttribute('data-bs-theme', savedTheme);
        themeIcon.className = savedTheme === 'dark' ? 'bi bi-moon' : 'bi bi-sun';

        document.getElementById('themeToggle').addEventListener('click', () => {
            const current = document.documentElement.getAttribute('data-bs-theme');
            const next = current === 'light' ? 'dark' : 'light';
            document.documentElement.setAttribute('data-bs-theme', next);
            themeIcon.className = next === 'dark' ? 'bi bi-moon' : 'bi bi-sun';
            localStorage.setItem('theme', next);
        });

        // Confirmación de cierre de sesión
        const logoutBtn = document.getElementById('btnLogout');
        const logoutConfirm = document.getElementById('logoutConfirm');
        const cancelLogout = document.getElementById('cancelLogout');

        logoutBtn.addEventListener('click', () => {
            logoutConfirm.style.display = 'block';
        });

        cancelLogout.addEventListener('click', () => {
            logoutConfirm.style.display = 'none';
        });
    </script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>